### ISSUE TITLE
Why Ping() function doesn't work?

### ISSUE THREAD

**Issue by dimuska139** [jinzhu/gorm#2264]
### What version of Go are you using (`go version`)?
go version go1.11.2 linux/amd64

### Which database and its version are you using?
postgres:9.6

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**
I am trying to display the text of error when the database becomes inaccessible while program is running. First I launch the database container, then run a go-program. Program checks connection in the infinite loop and prints "Connected" if database available. I use Ping() function to check it. Then, while the program is running, I stop docker-container to imitate the inaccessibility of the database. But the program continues to print text "Connected". Why Ping() function doesn't return error?

Need to runnable with [GORM's docker compose config](https://github.com/jinzhu/gorm/blob/master/docker-compose.yml) or please provides your config.

#### docker-compose.yml
```yml
version: '2'

services:
  db:
    image: postgres:9.6
    ports:
      - 766:5432
    environment:
      - POSTGRES_USER=notifications
      - POSTGRES_PASSWORD=12345
      - PGDATA=/var/lib/postgresql/data/pgdata
```
#### main.go
```go
package main

import (
	"fmt"
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/postgres"
	"time"
)

func main() {
	db, err := gorm.Open("postgres", "postgres://notifications:12345@localhost:766/notifications?sslmode=disable")

	if err != nil {
		fmt.Println(err)
		return
	}

	for {
		pingErr := db.DB().Ping()
		if pingErr != nil {
			fmt.Println(pingErr)
		} else {
			fmt.Println("Connected")
		}
		time.Sleep(time.Duration(3) * time.Second)
	}
}
```
