### ISSUE TITLE
Custom Column Names

### ISSUE THREAD

**Issue by pedromorgan** [jinzhu/gorm#674]
I'm developing and app and want to be able to define/override the columns.
https://github.com/daffodil/go-mailkit

I understand TableName() and looking for similar
```go
func(me Domain) TableName() string {
```

And also see the way to define column names in struct{} tags..
```go
 AnimalId    int64     `gorm:"column:beast_id;primary_key"`
```

As i understand, there is not way to "modify" the tags.. ie static compile..

Is there a trick to get around this ?

**Comment by pedromorgan** [comment]
Here's a flavour of the yaml configuration I want to load..  Its legacy db, but also this way "plugginable" to other systems

```yaml
db:
  engine: mysql
  datasource: "root:root@/mailserver_pfa"
  debug: true
  table_prefix: "postfix_"
  table_names:
    admin: admin
    alias: alias
         column_names:
              address: email
               x_col: new_col
    alias_domain: alias_domain
```
